### ISSUE TITLE
Override config for cs-firewall-bouncer with ansible

### ISSUE THREAD

**Issue by papanito** [papanito/ansible-role-crowdsec#3]
Installing [cs-firewall-bouncer](https://hub.crowdsec.net/author/crowdsecurity/bouncers/cs-firewall-bouncer) comes with a predefined config. It may make sense that this can be overridden, providing the config as an additional ansible parameter e.g.

```yaml
bouncers:
  cs-firewall-bouncer 
    url: https://github.com/crowdsecurity/cs-firewall-bouncer/releases/download/
    version: v0.0.12
    config: |
        mode: iptables
        pid_dir: /var/run/
        update_frequency: 10s
        daemonize: true
        log_mode: file
        log_dir: /var/log/
        log_level: info
        api_url: <API_URL>  # when install, default is "localhost:8080"
        api_key: <API_KEY>  # Add your API key generated with `cscli bouncers add --name <bouncer_name>`
        disable_ipv6: false
        deny_mode: DROP
        deny_log: false
        #deny_log_prefix: "crowdsec: "
        #if present, insert rule in those chains
        iptables_chains:
        - INPUT
        - FORWARD
```
